# Generated by Django 3.1.1 on 2021-01-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210107_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['position'], 'verbose_name_plural': 'Тип продукта'},
        ),
        migrations.AddField(
            model_name='producttype',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Должность'),
        ),
    ]
