# Generated by Django 3.1.1 on 2021-01-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210107_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['position'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name_plural': 'Тип продукта'},
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='position',
        ),
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Должность'),
        ),
    ]
