# Generated by Django 3.1.1 on 2021-01-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home-image/%Y/%m/%d/', verbose_name='Образ:')),
                ('caption', models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок: ')),
            ],
            options={
                'verbose_name': 'Главная',
                'verbose_name_plural': 'Главная',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news-image/%Y/%m/%d/', verbose_name='Образ:')),
                ('caption', models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок: ')),
            ],
            options={
                'verbose_name': 'Новый',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='ToolVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='tool-video/%Y/%m/%d/', verbose_name='Bидео')),
                ('name', models.CharField(max_length=200, verbose_name='заглавие')),
            ],
            options={
                'verbose_name_plural': 'Инструменты Vdieo',
            },
        ),
    ]
